# Generated by Django 4.1 on 2022-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='message',
            field=models.CharField(max_length=800),
        ),
    ]
