# Generated by Django 4.1 on 2022-09-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_tickets_email_alter_tickets_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='create_time',
        ),
    ]
