# Generated by Django 4.1 on 2022-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0003_remove_tickets_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=505)),
            ],
        ),
    ]
